export enum SCREEN {
  Profile = 'ProfileScreen',
  Home = 'HomeScreen',
  Location = 'LocationScreen',
  Scan = 'ScanScreen',
  Finance = 'FinanceScreen',
  Splash = 'SplashScreen',
  LogIn = 'LoginScreen',
  SignUp = 'SignUpScreen',
  SignUpConfirm = 'SignUpCreditConfirmScreen',
  SignUpViaCredit = 'SignUpViaCredit',
  SignUpCongrats = 'SignUpCongratsScreen',
  Landing = 'LandingScreen',
  InstantSignup = 'InstantSignUp',
  InstantCongrats = 'InstantCongratsScreen',
  FinanacePayemnt = 'FinancePaymentScreen',
  ProfileDetails = 'ProfileDetailsScreen',
}
